"""init tables

Revision ID: 4dae77c79e32
Revises: 
Create Date: 2026-06-01 13:33:33.257592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dae77c79e32'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique_courier_region'), 'courier_regions', type_='unique')
    op.drop_constraint(op.f('fk_courier'), 'courier_regions', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_courier'), 'courier_regions', 'couriers', ['courier_id'], ['courier_id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('unique_courier_region'), 'courier_regions', ['courier_id', 'region'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
